FROM python:3.10-slim

# Thư mục chạy app trong container
WORKDIR /app

# Copy requirements trước (nếu có)
COPY web_server/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy source Flask app
COPY web_server/ .

EXPOSE 5000

CMD ["python", "server.py"]
